#Workflow to publish containers in a registry

name: publish-containers
run-name: ${{ github.actor }} builds and publishes containers
on:
  release:
    types: [published]
jobs:
  matrix:
    name: Matrix Jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [nginx, sql]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
            image: 'eu.gcr.io/${{ secrets.PROJECT_ID }}/${{ matrix.folder }}:latest'
            service: '${{ matrix.folder }}'