#Workflow to publish containers in a registry

name: publish-containers
run-name: ${{ github.actor }} builds and publishes containers
on:
  push:
    branches:
      - main
jobs:
  matrix:
    name: Matrix Jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [nginx, sql]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          # gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }} # can be base64 encoded or plain text || not needed if you use google-github-actions/auth
          registry: eu.gcr.io
          project_id: ${{ secrets.PROJECT_ID }}
          image_name: ${{ matrix.folder }}
          image_tag: latest
          dockerfile: ./containers/${{ matrix.folder }}/Dockerfile
          context: .

      - uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
            image: 'eu.gcr.io/projetb3-386509/${{ matrix.folder }}:latest'
            service: '${{ matrix.folder }}'